import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import FooterWorkPage from "./components/footerWorkPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function OurWorkPageLayout({
  children,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html>
      <body>
        <div className="relative z-0">
          {children}
          <FooterWorkPage />
        </div>
      </body>
    </html>
  );
}
