import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LanguageProvider from "@/context/LanguageProvider";
import { ThemeProvider } from "@/context/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import { NavbarNew, Footer } from "@/components";
import DataProvider from "@/context/DataProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Takhi",
  description: "Generated by create next app",
  keywords: "",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            <DataProvider>
              <main>
                <NavbarNew />
                <div className="sm:ml-[102px] pt-20 sm:pt-0">{children}</div>
                <Toaster />
              </main>
            </DataProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
